### ISSUE TITLE
Support gang-scheduling by kube-batch

### ISSUE THREAD

**Issue by k82cn** [kubeflow/mxnet-operator#16]
Gang-scheduling is a common requirement from training job; kube-batch supports it right now. So it's better to do the integration for training jobs.

**Comment by suleisl2000** [comment]
@k82cn mxnet-operator v2 is based on tf-operator shared implementation and mxnet-operator support the feature. You can have a try.

Thanks,
Lei

**Comment by suleisl2000** [comment]
@k82cn, thanks for your contribution :)

For now, we reuse controller from tf-operator which already included kube-batch. AFAIK, `kube-batch` prefer to use `PodGroup`; and if any other improvements, please let us know :)

**Comment by k82cn** [comment]
> and if any other improvements, please let us know :)

Yes; for now kube-batch also support some other enhancement, e.g. `Queue` ; we'd like to enhance them together.

BTW, we're also working an enhanced/advanced job management layer for batch workload; maybe we can also try to integrate it with mxnet-operator which will save your effort on error handling.

**Comment by Jeffwan** [comment]
@k82cn We will migrate to volcano directly when we graduate mxnet-operator to v1.

**Comment by k82cn** [comment]
> @k82cn We will migrate to volcano directly when we graduate mxnet-operator to v1.

That's great !

**Comment by Jeffwan** [comment]
This has been supported since current mxnet use latest kubeflow/common.
