### ISSUE TITLE
[feature] Implement V2

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/mxnet-operator#2]

**Comment by suleisl2000** [comment]
We are working on it.

/cc @jzp1025

**Comment by jzp1025** [comment]
I will request a WIP PR with the first edition for code reviewing in the next week.
According to [pytorch.v2](https://github.com/kubeflow/tf-operator/pull/786)

**Comment by gaocegege** [comment]
Thanks for your contribution! @jzp1025
