### ISSUE TITLE
how to create a mxjob in go?

### ISSUE THREAD

**Issue by yangwenhuan** [kubeflow/mxnet-operator#51]

**Comment by gaocegege** [comment]
You need to create the client for MXNetJob then use that client to CRUD the CRD

**Comment by yangwenhuan** [comment]
> You need to create the client for MXNetJob then use that client to CRUD the CRD

Is there any go api for CRUD the CRD mxjob?

**Comment by gaocegege** [comment]
https://github.com/kubeflow/mxnet-operator/tree/master/pkg/client/clientset/versioned

**Comment by gaocegege** [comment]
/close

I am closing it but feel free to comment if you have problems on it.

**Comment by yangwenhuan** [comment]
> https://github.com/kubeflow/mxnet-operator/tree/master/pkg/client/clientset/versioned

Could you offer me the v1alpha1 api version?

**Comment by gaocegege** [comment]
@yangwenhuan We deprecate v1alpha1, thus do not suggest using that version. But if you still want to use, try https://github.com/kubeflow/mxnet-operator/tree/8b18864a467a0cd9603bbb2a7c1c70185aa7e313/pkg/client/clientset/versioned

**Comment by yangwenhuan** [comment]
> @yangwenhuan We deprecate v1alpha1, thus do not suggest using that version. But if you still want to use, try https://github.com/kubeflow/mxnet-operator/tree/8b18864a467a0cd9603bbb2a7c1c70185aa7e313/pkg/client/clientset/versioned

thanks a lot for your help!
