### ISSUE TITLE
Establish CI tests for v1alpha2

### ISSUE THREAD

**Issue by jzp1025** [kubeflow/mxnet-operator#8]
Hi , I'm working on the unit tests for v1alpha2 now.
Any guidance or examples about how to set up the CI tests ?
Thanks !
@gaocegege

**Comment by johnugeorge** [comment]
Unfortunately no. 

In case of pytorch operator repo,  you can trace the calls easily from the prow config file which defines the ksonnet app to run. 
https://github.com/kubeflow/pytorch-operator/blob/master/prow_config.yaml

As the config points to, it runs the ksonnet app at https://github.com/kubeflow/pytorch-operator/tree/master/test/workflows

**Comment by jzp1025** [comment]
#10

**Comment by suleisl2000** [comment]
CI support is handled at #37, close it.
